# Generated by Django 5.0.2 on 2024-03-05 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0003_remove_company_industry_alter_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='location',
            new_name='other_location',
        ),
    ]
