# Generated by Django 5.0.2 on 2024-03-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0004_rename_location_company_other_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='other_location',
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('private company', 'Private Company'), ('associate company', 'Associate company'), ('government', 'Government')], max_length=40),
        ),
    ]
