# Generated by Django 5.0.2 on 2024-03-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0007_alter_company_city_alter_company_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default='', max_length=300),
        ),
    ]
