# Generated by Django 5.0.2 on 2024-03-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0009_alter_user_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(max_length=300),
        ),
    ]
