# Generated by Django 5.0.2 on 2024-03-06 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0010_alter_user_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
    ]
