# Generated by Django 5.0.2 on 2024-03-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0014_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
