# Generated by Django 5.0.2 on 2024-03-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0016_alter_department_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'company')},
        ),
        migrations.AlterModelTable(
            name='department',
            table=None,
        ),
    ]
