# Generated by Django 5.0.2 on 2024-03-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0018_rename_company_companies_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='departments',
            constraint=models.UniqueConstraint(fields=('name', 'company'), name='unique_department_per_company'),
        ),
    ]
