# Generated by Django 5.0.2 on 2024-03-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0020_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='about',
            field=models.TextField(default='No information provided'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(choices=[('manager', 'Manager'), ('developer', 'Developer'), ('designer', 'Designer'), ('analyst', 'Analyst')], max_length=100),
        ),
    ]
