# Generated by Django 5.0.2 on 2024-03-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0021_employees_about_alter_employees_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
