# Generated by Django 5.0.2 on 2024-03-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0022_alter_employees_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='about',
            field=models.TextField(max_length=255),
        ),
    ]
