# Generated by Django 5.0.2 on 2024-03-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0023_alter_employees_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='user',
        ),
        migrations.AddField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
