# Generated by Django 5.0.2 on 2024-03-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0024_remove_employees_user_employees_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
