# Generated by Django 5.0.2 on 2024-03-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0025_alter_employees_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='company',
        ),
    ]
