# Generated by Django 5.0.2 on 2024-03-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0026_remove_employees_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
